### ISSUE TITLE
undefined: prometheus.RegisterOrGet

### ISSUE THREAD

**Issue by huiser** [stigsb/varnish_request_exporter#2]
Installation fails:
    go get github.com/stigsb/varnishncsa_exporter
    # github.com/stigsb/varnishncsa_exporter
    go/src/github.com/stigsb/varnishncsa_exporter/varnish_request_exporter.go:117:22: undefined: 
    prometheus.RegisterOrGet

**Comment by dani-bl** [comment]
same issue her:

~/Downloads/test/varnish_request_exporter-master$ go get github.com/stigsb/varnishncsa_exporter
# github.com/stigsb/varnishncsa_exporter
../../../src/github.com/stigsb/varnishncsa_exporter/varnish_request_exporter.go:117: undefined: prometheus.RegisterOrGet

**Comment by stigsb** [comment]
Should be fixed now (v0.13)
